### ISSUE TITLE
cannot use crossbario as router

### ISSUE THREAD

**Issue by evanorsouw** [darrenjs/wampcc#12] opened 2017-09-18 07:57 UTC
I created a single application that contains both router and client functionality to quickly test functionality. The code is exactly from the provided examples and works well. [test code](https://github.com/darrenjs/wampcc/files/1309993/wampcc.test.code.txt)

Next I removed the router section and tried to connect to a crossbario router instance.
This failed with the attached [wampcc logging](https://github.com/darrenjs/wampcc/files/1309986/wampcc.logging.connecting.to.crossbario.txt)

Unfortunately since I am new wamp I am not yet able to fully grasp where or why it fails.

**Comment by darrenjs** [comment] 2017-09-18 09:57
Hi, using your logs, I've tested this and I think I've found what the problem is.  

The wampcc library will need a couple of small changes to make it compatible with crossbar.  It might take a day or two to properly make these changes.  However in the short term, I have created a new branch  `crossbar_compat`, which add in  simple work-arounds.  With that branch I am able to connect to the demo crossbar.io router (the one that they provide as a docker image), and call procedures etc.   E.g. using the wampcc-admin program:  `admin 127.0.0.1 8080  -R realm1 -p com.example.oncounter --arglist '["hi"]' -d -d`

What you could do for now, is switch to using the `crossbar_compat`, which should allow you to continue making progress, then later switch back master once the fixes are properly integrated.

**Comment by evanorsouw** [comment] 2017-09-18 12:05
Hi, thanks for your quick response.
For the time being I am ok with sticking to embedded router (which is the initial reason for using wampcc) but in the longer we would also like to use crossbar as router as well that's why I did a quick test.

**Comment by darrenjs** [comment] 2017-11-04 15:21
fixed as of version 1.5

**Closed** 2017-11-04 15:21 UTC
